# **INTRO TO TENSORFLOW**


In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
#creating a scaler
scaler = tf.constant(9)
print(scaler)

tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
#checking the dimension of the scaler
scaler.ndim

0

In [ ]:
vector = tf.constant([10,10]) #we have put a constant list inside the tensor
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#checking the dimension of the vector
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10, 7],
                     [7, 10]])
print(matrix)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

### By default we get int32 as dtype which is basically the 32 bit precision

the higher the number like int 64 the higher the precision

In [ ]:
#another matrix
another_matrix = tf.constant([[1., 2.],
                              [3., 4.],
                              [6., 7.]], dtype = tf.float16)  #we specified the data type
print(another_matrix)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [6. 7.]], shape=(3, 2), dtype=float16)


In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [6., 7.]], dtype=float16)>

In [ ]:
#dimension of the matrix
another_matrix.ndim

2

In [ ]:
#dimension of the matrix
matrix.ndim

2

### TENSORS

When we had a constant it had just 0 dimension a list had 1 and a matrix had 2.
Now if we want to increase the dimension more than 2 we are going to crete a tenor

In [ ]:
tensor = tf.constant([
                   [[1,2,3],
                    [4,5,6]],

                    [[7,8,9],
                     [10,11,12]],
                    
                    [[13,14,15],
                     [16,17,18]]
                    ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

THROUGH THIS COURSE WE WILL REFFER EVERYTHING AS A TENSOR ONLY

What we have learned

* Scaler : a single number
* Vector : a number with direction
* Matrix : a 2-D array of numbers
* Tensor : an n-dimesnion array

### **Creating a tensors with 'tf.variable'**

In [2]:
#creating a same tensor as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try changing one of its element 
changeable_tensor[0] = 7

TypeError: ignored

In [3]:
#this shows an error when we directly try to change a tensor

''' Using the .assign(value) '''

changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [4]:
#doing this with unchangeable_tesnor

unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
unchangeable_tensor[0] = 7

TypeError: ignored

In [6]:
#using the assign attribute

unchangeable_tensor[0].assign(7)

AttributeError: ignored

### Creating random tesnors

In [ ]:
Random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
Random_1 = Random_1.normal(shape = (3,2))
Random_2 = tf.random.Generator.from_seed(42)
Random_2 = Random_2.normal(shape = (3,2))

Random_1, Random_2, Random_1 == Random_2 # the equaity gives a matrix showing true to the corresponding element is same in  both the matrix

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# there is a two type distribution we can use when making a random tensor a normal or a uniform 
'''Check the documentation for further details'''

### Shuffling the order of the elements in a tensor


In [7]:
not_shuffled = tf.constant([[1, 2],
                              [3, 4],
                              [6, 7]]) 
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [6, 7]], dtype=int32)>

In [17]:
#shuffling the tensor 
tf.random.shuffle(not_shuffled)
# we can see that the tensor is shuffled about its first dimension'''

# we get random order each time we run it

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [3, 4],
       [1, 2]], dtype=int32)>

In [13]:
# what if we set seed value
tf.random.set_seed(42)     # This is the global level random seed
tf.random.shuffle(not_shuffled)

# we get the same sequence no matter how many times we run it

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [6, 7],
       [1, 2]], dtype=int32)>

In [15]:
# this way doesnt keep the sequence same
tf.random.shuffle(not_shuffled, seed = 42)   # This is the operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [1, 2],
       [3, 4]], dtype=int32)>

If we want the shuffled tensor to be of same sequence and it doesnt change each time we run it then we must use the Global level tesnor  OR global along with the operation level

### Other ways of creating a tensor



In [18]:
tf.ones(shape = (10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

we can initialise the shape either way with () or [] and there is no need to write
**' shape = (5,5) '**

In [19]:
tf.zeros((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into Tensors

In [20]:
import numpy as np

In [21]:
numpy_A = np.arange(1,25 , dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
d = tf.constant(numpy_A, shape = (2, -1, -1))
d

ValueError: ignored

In [24]:
# Numpy array turned into tensor
A = tf.constant(numpy_A, shape = (2,3,4)) #3-D tensor
B = tf.constant(numpy_A) # original 
c = tf.constant(numpy_A, shape = (3,8)) # 2-D tensor
A, B, c

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

### Getting information from tensor


* Size
* Rank
* Shape
* axis or dimension



In [25]:
# Creating a rank 4 tensor
rank_4_tensor = tf.zeros((2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.ndim, rank_4_tensor.shape, rank_4_tensor.shape[0],  rank_4_tensor.shape[1], tf.size(rank_4_tensor)

(4,
 TensorShape([2, 3, 4, 5]),
 2,
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
2*3*5*4

120

In [30]:
print("Datatype:", rank_4_tensor.dtype)
print("Dimension or (rank):", rank_4_tensor.ndim)
print("shape:", rank_4_tensor.shape)
print("element along 0 axis", rank_4_tensor.shape[0])
print("element along last axis", rank_4_tensor.shape[-1]) # for last we use -1
print("Total element", tf.size(rank_4_tensor)) # AS A TENSOR
print("Total element", tf.size(rank_4_tensor).numpy()) # AS A NumPy

Datatype: <dtype: 'float32'>
Dimension or (rank): 4
shape: (2, 3, 4, 5)
element along 0 axis 2
element along last axis 5
Total element tf.Tensor(120, shape=(), dtype=int32)
Total element 120


### Indexing Tensors

Tensors can be indexed like python list

In [31]:
some_list = [1,2,3,4]
some_list[ : 2] # getting the first 2 element of the list

[1, 2]

In [35]:
#getting the first 2 element from each dimension 

rank_4_tensor[:1, :2, : 2, : 2]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[:2, :2, : 2, : 2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# getting the 1 element from each dimension except the last one

listt = [1,2,3,4]
listt[ : ] # this gives all the element

[1, 2, 3, 4]

In [38]:
# getting the 1 element from each dimension except the last one
rank_4_tensor[:1, :1, :1, : ]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

Adding an extra dimension at the end of the existing dimension 

In [39]:
# making a 2-D tensor

rank_2_tensor = tf.constant([[10,7], 
                             [7,10]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [40]:
# getting the last element of each row of our tensor
rank_2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# adding an extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # here ... --> [:, :], tf.newaxis
rank_3_tensor

In [41]:
#alternative of using newaxis
tf.expand_dims(rank_2_tensor, axis = -1) #inserting the extra dimension at the end

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [42]:
tf.expand_dims(rank_2_tensor, axis = 0) #inserting the extra dimension at the start

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]], dtype=int32)>

### Basic Operations 
'-' , '+' , '*' , '/'

In [ ]:
tensor = tf.constant([[10,7],
                      [7,10]])
tensor

In [ ]:
# adding a 10 to the tensor we got
tensor + 10 , tensor # we can see that the original tensor is still unchanged 


In [ ]:
#alternative to add a number to a tensor 
tf.add(tensor, 10)
# we can add two tensors as well instead of 10 pass the other tensor which we want to add

In [ ]:
tensor - 10

### Matrix Multiplication


In [50]:
tensor = tf.constant([[10,7],
                      [7,10]])

#multiplying the matrix
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [51]:
tensor * tensor # this doesnt multiply the tensors it just multiplies the corresponding elements 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 49, 100]], dtype=int32)>

using the ' @ ' symbol to multiply the matrix in python


In [52]:
# using @ symbol to multiply the matrix in python
tensor @ tensor  

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [57]:
X = tf.constant([[1,2],
                 [2,3],
                 [3,4]])

Y = tf.constant([[9,8],
                 [7,6],
                 [5,4]])


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[9, 8],
        [7, 6],
        [5, 4]], dtype=int32)>)

### **Thus we need to take care about the order of the matrix we are multiplying**

In [58]:
X@Y

InvalidArgumentError: ignored

In [55]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

###Reshaping

In [59]:
tf.reshape(Y, shape = (2, 3))
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 8],
       [7, 6],
       [5, 4]], dtype=int32)>

In [ ]:
X @ Y

In [ ]:
tf.matmul(X, Y)

In [ ]:
Y

In [ ]:
# taking the transpose of the matrix
Z = tf.transpose(X)
Z

In [ ]:
# transpose and reshape are different 
# reshape just changes the shape like puts the element here and there

**dot product**

matrix multiplication can be done using 
* tf.matmul()
* tf.tensordot()


In [ ]:
X, Y

In [ ]:
X = tf.constant([[1,2],
                 [2,3],
                 [3,4]])

Y = tf.constant([[9,8],
                 [7,6],
                 [5,4]])

In [ ]:
X, Y

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

we generally use transform majorly when dealing with matrix multiplicatin instead of the reshape when doing the probelem

### Changing the datatype of the tensors

In [ ]:
A = tf.constant([10, 7])
A.dtype

In [ ]:
B = tf.constant([1.4, 7.4])
B.dtype

In [ ]:
C = tf.cast(B, tf.int32)
C, C.dtype

In [ ]:
D = tf.cast(A, tf.float32)
D, D.dtype

### Aggregating Tenors 

Aggregating means condensing tensors from multiple value to a smaller amount of value tensors 

In [ ]:
# Get the absoute value
E = tf.constant([-10, -7])
E

In [ ]:
# this gives the absolute value of a negative tensor
tf.abs(E)

Lets go through the following form of aggregation 
* Get the making
* Get the minimum
* Get the mean of the tensor
* Get the sum of the tensor


In [60]:
# Creating a random tensor
F = tf.constant(np.random.randint(0, 100, size = 50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15, 18, 84, 76, 99, 60, 68, 86, 79, 35, 46, 25, 60, 88, 37, 81, 19,
       20, 41, 83,  0, 95, 11, 99, 38, 77, 24, 44,  0, 32, 26, 82, 65, 41,
       12, 81, 95, 96, 82, 19, 22, 45, 43, 65, 68, 57, 14, 57, 21, 79])>

In [61]:
# Finding the minimum of the 
'''it is similar to numpy where we use np.min(F) but in tensorflow there is a convention to use reduce_min'''

tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [62]:
# Finding the Max
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [63]:
# Finding the Sum
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2610>

In [64]:
# Finding the mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [65]:
# Finding the Variance
tf.reduce_std(F) # this wont work

'''tf.reduce_variance''' # this will also not work

AttributeError: ignored

In [66]:
# finding the variance
import tensorflow_probability as tfp
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=863>

In [67]:
#finding the standard deviation
F = tf.cast(F, dtype = tf.float16)
tfp.stats.stddev(F)

<tf.Tensor: shape=(), dtype=float16, numpy=29.39>

In [68]:
F = tf.cast(F, dtype = tf.float32)
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float32, numpy=29.37618>

In [ ]:
# better approach instead of writing F seperately
tf.math.reduce_std(tf.cast(F, dtype = tf.float32)) 

In [ ]:
tf.math.reduce_variance(F)

### Finding the positional minimun and maximum 

In [70]:
G = tf.random.set_seed(40)
G = tf.random.uniform(shape = [50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.54513085, 0.7588961 , 0.8362565 , 0.39474642, 0.72001076,
       0.6402768 , 0.15894496, 0.57128036, 0.41122293, 0.18993318,
       0.2312665 , 0.7875649 , 0.18806243, 0.8033031 , 0.12747478,
       0.43258965, 0.98803484, 0.8451586 , 0.9797807 , 0.9952853 ,
       0.6283821 , 0.8643936 , 0.9500631 , 0.41532683, 0.388798  ,
       0.33959448, 0.36432612, 0.79217136, 0.90930283, 0.6459546 ,
       0.4547919 , 0.3669002 , 0.22951639, 0.54661405, 0.9371824 ,
       0.04014015, 0.82825315, 0.45409238, 0.943413  , 0.20978856,
       0.1274836 , 0.9666685 , 0.97015405, 0.568432  , 0.99477863,
       0.39956594, 0.3263564 , 0.61465824, 0.24279046, 0.03102553],
      dtype=float32)>

In [71]:
# to find the positional maximum
tf.argmax(G) # position where there is max value element

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [72]:
# finding the value on the index we got max value
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9952853>

In [73]:
#the max element in the tensor
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9952853>

In [ ]:
# checking weather the two are equal or not
G[tf.argmax(G)] == tf.reduce_max(G)

In [ ]:
# to find the positional minimum
tf.argmin(G)

In [ ]:
# finding the value on the index we got min value
G[tf.argmin(G)]

### Squeezing a Tensor (removing all single dimension)

In [74]:
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [75]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [76]:
H_squeezed = tf.squeeze(H)
H_squeezed, H_squeezed.shape
# this will remove all the single one elements from a tensor 
# the new shape is [50]

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One hot encodin of tensors
when we have words as input for a feature then we use one hot encoding like it turn features like red blue green too 1 and 0 

In [77]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth = 4) # depth as for a 4x4 we have 4 elements and we want to get a 4x4 matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
'''
      [[1., 0., 0., 0.],  <-- this row depicts the number 0
       [0., 1., 0., 0.],  <-- this row depicts the number 1
       [0., 0., 1., 0.],  <--this row depicts the number 2
       [0., 0., 0., 1.]]  <--this row depicts the number 3
       '''

In [ ]:
tf.one_hot(some_list, depth = 4 , on_value = 'hello', off_value= 'why') # if we wish to use any other value instead of 1 or 0 we thus there use on_value and off_value

### Square, log , Square root

In [ ]:
# create a new tensor
I = tf.range(1, 10)
I

In [ ]:
tf.square(I)

In [ ]:
tf.sqrt(I) # this takes float point value

In [ ]:
tf.sqrt(tf.cast(I, dtype = tf.float32))

In [ ]:
tf.math.log(tf.cast(I, dtype = tf.float32))

### Tensors and NumPy
tensorflow has faster numerical processing

In [ ]:
# creating a tensor from a numpy array
J = tf.constant(np.array([1. , 2. , 3. , 4.]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [ ]:
# Convert our tensor back to numpy array
np.array(J), type(np.array(J))

(array([1., 2., 3., 4.]), numpy.ndarray)

In [ ]:
J.numpy, type(J.numpy())

(<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>>,
 numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [ ]:
J.numpy()

(array([3.], dtype=float32), 3.0)

In [ ]:
J.numpy()[0] # when just want the element

3.0

In [ ]:
# default data types of each 

numpy_J = tf.constant(np.array([3., 7., 10.,]))
tensor_J = tf.constant([3., 7., 10.])

# checking the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
# thus we can conclude the tensor made with numpy has greater value as compaired to the one made directly in the tensorflow

### Finding access to the GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices('GPU') # to check for GPU specifically

[]